services:
  jenkins:
    image: jenkins/jenkins:${JENKINS_VERSION}
    user: "${JENKINS_UID}:${JENKINS_GID}"   #jenkins-docker:docker user:grp on host
    container_name: jenkins
    command: >
      bash -c "java -jar /usr/share/jenkins/jenkins.war --prefix=/jenkins"
    ports:
      - "${JENKINS_HOST_PORT}:8080"   # host access open for github webhooks
      - "50000:50000" # agent connections
    volumes:
      - jenkins_home:/var/jenkins_home
      # docker socket from host mounted to create/access pods for builds
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gateway_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/jenkins/login || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  gateway_net:
    external: true
