spring:
  cloud:
    gateway:
      routes:
        - id: jenkins-service
          uri: ${JENKINS_INTERNAL_URL:-http://jenkins:8080}
          order: 1
          predicates:
            - Path=/jenkins/**
          filters:
            - PreserveHostHeader
        - id: keycloak-service
          uri: ${KEYCLOAK_INTERNAL_URL:-http://keycloak:8080}
          order: 0
          predicates:
            - Path=/keycloak/**
          filters:
            - AddResponseHeader=Cache-Control,no-store,no-cache,must-revalidate,max-age=0
            - AddResponseHeader=Pragma,no-cache
            - StripPrefix=1
            - PreserveHostHeader
            - AddRequestHeader=X-Forwarded-Proto,https
            - AddRequestHeader=X-Forwarded-Port,443