services:
  api-gateway:
    image: jeshupatelg/apigw-homeserver:ed6
    container_name: api-gateway
    ports:
      - "192.168.29.96:2345:8080"   # expose gateway externally
    volumes:
      - ./routes.yaml:/config/routes.yaml:ro
    networks:
      - gateway_net
    restart: unless-stopped

networks:
  gateway_net:
    external: true